# .circleci/config.yml
version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: "run test"
          command: |
            . venv/bin/activate
            pytest -v --cov=calculator

workflows:
  say-hello-workflow:
    jobs:
      - say-hello